### ISSUE TITLE
Tile enchantments

### ISSUE THREAD

**Issue by filfat** [SniperGER/Redstone#11]
Some tile uses a full image to cover the tile (let's take Minecraft as an example again). This could also perhaps be a toggle in the tile plist.

- [x] Full image Tile
- [ ] Colored icon Tile
- [x] Name-less Tile

**Comment by SniperGER** [comment]
Just leaving a reference to #10 here as it is basically the same feature.

**Comment by SniperGER** [comment]
Use these tile.plist keys to achieve what you wanted:

`BOOL TileLabelHidden`: Hide the label for all sizes
`BOOL UsesCornerBadge`: Use a corner badge instead of the icon badge
`BOOL HasColoredIcon`: Allows you to have colored icons while not having to use full size artwork
