### ISSUE TITLE
Search problems launching apps 

### ISSUE THREAD

**Issue by butters22** [SniperGER/Redstone#15]
When using the search feature I can't click the app to launch it, it doesn't respond. I have to scroll to the app to launch it.

**Comment by SniperGER** [comment]
Thanks for noting. It's because the user interaction gets disabled once the app is out of sight, but doesn't get reenabled when displayed in Search. This was one of the many attempts to fix the App List glitches, but didn't really do anything. I'll remove it in the next few minutes

**Comment by SniperGER** [comment]
Fixed with 52a306c.
