### ISSUE TITLE
Tile Badges

### ISSUE THREAD

**Issue by filfat** [SniperGER/Redstone#16]
Some tiles in Windows uses badges instead of displaying the count next to the icon (Messenger & Mail is a great example of this). We should support this on a per-tile (including size) basis in the plist.

For reference,
https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-badges

**Comment by SniperGER** [comment]
f1628d1 adds the `UsesCornerBadge` and `CornerBadgeForSizes` keys to enable the corner badge for every size or selected sizes respectively.
