### ISSUE TITLE
Tiles scattered everywhere, cause unknown

### ISSUE THREAD

**Issue by butters22** [SniperGER/Redstone#18]
First off, the tile editing is very buggy. They went all over the screen and I couldn't move them to the right place. Second, I tried to remove them all and restart but now every time my phone goes into safe mode and when I restart it just goes back into safe mode. Reinstalling doesn't fix.

**Comment by SniperGER** [comment]
Unpinning all tiles has been fixed with 3f4a365.

To reset Redstone, remove its config file located at `/var/mobile/Library/Preferences/ml.festival.redstone`. This will reset your tile layout, accent color and Lock Screen switch.

**Comment by SniperGER** [comment]
I've just experienced the bug where the tiles are scattered all over the place. I really don't know what caused it, but I'll have a look at it.

**Comment by SniperGER** [comment]
Should be fixed with cb56bd1. If not, just reopen and explain what you did to trigger this glitch.
