### ISSUE TITLE
What does "commits" mean?

### ISSUE THREAD

**Issue by butters22** [SniperGER/Redstone#19]

**Comment by butters22** [comment]
Does that mean a future update?

**Comment by SniperGER** [comment]
Commits can be seen as a kind of progress report. Every time I add a little feature or fix something, I commit it to the repo. The plan is to have nightly builds ready with the latest changes that will move into Snapshots (which are released in Cydia) to work towards a final release.

So basically it's what will be a future update.

**Comment by SniperGER** [comment]
Closed for not being an actual issue.
