### ISSUE TITLE
Question mark icons when entering edit mode

### ISSUE THREAD

**Issue by butters22** [SniperGER/Redstone#20]
When I hold a tile to move it the little icons on the top right and left have question marks.

**Comment by filfat** [comment]
Thats due to missing the fonts; did you install the nightly build?

**Comment by butters22** [comment]
Where do I install that from?

**Comment by SniperGER** [comment]
I didn't include the required fonts in the repo for legal reasons. If you have a Windows PC, copy the following files from `C:\Windows\Fonts` to `/var/mobile/Library/FESTIVAL/Redstone/Fonts` on your device:

- segmdl2.ttf (Segoe MDL2 Assets)
- segoeui.ttf (Segoe UI)
- segoeuil.ttf (Segoe UI Light)
- segoeuisl.ttf (Segoe UI Semilight)
