### ISSUE TITLE
No fonts folder in redstone

### ISSUE THREAD

**Issue by butters22** [SniperGER/Redstone#27]

**Comment by SniperGER** [comment]
#20

**Comment by butters22** [comment]
There's no fonts folder in the iPhone directory you gave me

**Comment by SniperGER** [comment]
Because I didn't include the Fonts folder, as explained above. You need to create it yourself if you're running a nightly build

**Comment by butters22** [comment]
So when I create the folder do I just add these

segmdl2.ttf (Segoe MDL2 Assets)
segoeui.ttf (Segoe UI)
segoeuil.ttf (Segoe UI Light)
segoeuisl.ttf (Segoe UI Semilight)
as .ttf files in the folder and then respring?

**Comment by SniperGER** [comment]
Yes, and for today's build add seguisb.ttf (Segoe UI Semibold) aswell. It's required for the notifications.

**Comment by butters22** [comment]
Sweet! Can't wait!
