### ISSUE TITLE
Could we get bigger icons on tiles?

### ISSUE THREAD

**Issue by butters22** [SniperGER/Redstone#31]
So instead of having a small square app icon on top of the blue tile can the whole tile be the app icon like this? https://www.windowscentral.com/sites/wpcentral.com/files/styles/xlarge_wm_blw/public/field/image/2015/07/Top_Free_Windows_Phone_Games.jpg?itok=XecKVh1W

**Comment by butters22** [comment]
Basically make the app icon fill the whole tile instead of being scaled down

**Comment by SniperGER** [comment]
Full size tile icons are already implemented. You just need correctly sized tile icons and enable the key `FullBleedArtwork` in that tiles property list.

Enabling full size tile icons for default icons (those that do not have tile icons) will just look bad. It's also not part of the Windows 10 design to do that (I'm doing this just like Windows 10 Desktop)
