### ISSUE TITLE
Added fonts folder and all fonts but still question marks

### ISSUE THREAD

**Issue by butters22** [SniperGER/Redstone#32]
I copied the font files from my computer to /bar/mobile/Library/FESTIVAL/Redstone/Fonts and resprung my device but I still have question marks when editing tiles and it seems like the fonts aren't working

**Comment by butters22** [comment]
I meant /var/

**Comment by SniperGER** [comment]
Have you copied the fonts from a device running Windows 10 1703 "Creators Update"? There is a possibility fonts copied from this version are not working on other operating systems.

**Comment by butters22** [comment]
I copied them from my windows 10 desktop, and sent them as an email and then copied them to filza and then into the fonts folder I created in redstone

**Comment by SniperGER** [comment]
In this case, the build number of your Windows 10 is important. Build 10.0.15063 is considered the "Creators Update" while Build 10.0.14393 is called the "Anniversary Update". Run `winver.exe` to check the version you're currently running.
