### ISSUE TITLE
Request readme for compile

### ISSUE THREAD

**Issue by imReker** [SniperGER/Redstone#36]
Please write a brief compile guide including environment or external tools required (such as TheOS).

I tried to compile the project directly within xcode and get many error due to absolute path problem in .sh

**Comment by SniperGER** [comment]
Will do

**Comment by SniperGER** [comment]
Build instructions are now available for the `rewrite` branch, but mostly apply to `master` aswell. Just ignore the libobjcipc part if you're building `master`.
