### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by filfat** [SniperGER/Redstone#6]
Something like this should in theory be easy to implement with Travis-CI now that they've added support for MacOS.

This would of course be more risk-filed than the snapshots but would also allow for faster feedback.

**Comment by SniperGER** [comment]
I've looked into Travis and it seems that it could work in theory. It's just that I need both Theos and the iOS 10.1 SDK, and I have really no idea how to set that up.

I will definitely consider this once I have more experience with Travis.

**Comment by SniperGER** [comment]
I have added Travis CI to the project. Now I just need to find out how to get the build output back to GitHub and display it in Releases.

**Comment by filfat** [comment]
See https://github.com/filfat-Studios-AB/3ds.js/blob/master/.travis.yml. You could also do something similar for FTP if you'd like to deploy to the repo.

Use https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables for things like API secrets or an FTP password & username.

**Comment by SniperGER** [comment]
Thanks for helping me out on this. Now I've got to wait to schedule the builds correctly (just like they used to be released Sundays at 8 pm)
