### ISSUE TITLE
Can we get more icons?

### ISSUE THREAD

**Issue by butters22** [SniperGER/Redstone#9]
I would love it if you could add icons for Instagram and Reddit and games as well. I'd like to be able to add more tiles to the screen but the x's are annoying.

**Comment by SniperGER** [comment]
I've changed the way tile icons are loaded in one of the latest commits (ignore all those Travis related ones). Instead of showing that default ("X") icon, the application icon is used if there are no tile icons. However, this isn't final yet.

**Comment by filfat** [comment]
For Reddit see #13.

**Comment by butters22** [comment]
You're the real MVP sniperGER
